"""
Simple migration runner for the password manager.

Usage:
    python migrate.py

What it does:
- Uses the Flask app config to point Alembic at the right database.
- Creates a new autogenerated revision (message can be overridden with MIGRATION_MESSAGE).
- Runs `upgrade` to head. No destructive operations are issued; existing data is not truncated.

Notes:
- If the database has no alembic_version table, we stamp the current state to avoid any accidental
  rebuilds and then proceed with an autogeneration + upgrade.
"""
from __future__ import annotations

import os
from pathlib import Path
from sqlalchemy import inspect
from flask_migrate import migrate, upgrade, stamp

from project import create_app, db


def ensure_version_table():
    """Stamp the database if alembic_version is missing, without touching data."""
    inspector = inspect(db.engine)
    if "alembic_version" not in inspector.get_table_names():
        stamp()  # baseline stamp; upgrade will still run new revisions


def run():
    app = create_app()
    with app.app_context():
        ensure_version_table()

        # First apply any pending migrations (safe, non-destructive)
        upgrade()

        # Optional autogenerate if requested
        if os.getenv("MIGRATION_AUTOGEN", "0") == "1":
            message = os.getenv("MIGRATION_MESSAGE", "auto-per-user-encryption")
            try:
                migrate(message=message)
            except BaseException as exc:  # catches SystemExit from flask-migrate
                if "not up to date" not in str(exc):
                    raise
                print("Database not up to date; skipping autogenerate; already upgraded.")
        print("Migration complete. Database schema is at head.")


if __name__ == "__main__":
    # Ensure script runs from project root so migrations/ is found
    os.chdir(Path(__file__).resolve().parent)
    run()
