"""auto-per-user-encryption

Revision ID: 18dfdb9f2eaa
Revises: b4e43f7dab29
Create Date: 2025-12-01 15:38:42.634477

"""
import base64
import os
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18dfdb9f2eaa'
down_revision = 'b4e43f7dab29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_payload', sa.Text(), server_default='', nullable=False))
        batch_op.alter_column('site',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_salt', sa.String(length=64), nullable=True))

    # Backfill salts for existing users to satisfy NOT NULL without touching credentials
    conn = op.get_bind()
    users_table = sa.table('users',
                           sa.column('id', sa.Integer),
                           sa.column('encryption_salt', sa.String(64)))
    results = conn.execute(sa.select(users_table.c.id)).fetchall()
    for row in results:
        salt = base64.urlsafe_b64encode(os.urandom(16)).decode()
        conn.execute(
            users_table.update().where(users_table.c.id == row.id).values(encryption_salt=salt)
        )

    # For any legacy passwords rows, ensure the new column is non-null (empty string placeholder)
    passwords_table = sa.table('passwords',
                               sa.column('id', sa.Integer),
                               sa.column('encrypted_payload', sa.Text))
    conn.execute(
        passwords_table.update().where(passwords_table.c.encrypted_payload == None).values(encrypted_payload='')
    )

    # Enforce NOT NULL after backfill
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('encryption_salt',
               existing_type=sa.String(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encryption_salt')

    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('site',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('encrypted_payload')

    # ### end Alembic commands ###
