"""Add categories and date_added with server default

Revision ID: b4e43f7dab29
Revises: 
Create Date: 2025-11-26 17:05:24.438471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4e43f7dab29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('password',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('additional_fields',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.alter_column('additional_fields',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
